source: src/
destination: build/
title: Michael Matyus
description: ğŸ¢
keywords:  michael matyus
permalink: pretty
collections:
  books:
    output: true
    permalink: /books/:title/
feed:
  collections:
    - books
plugins:
  - jekyll-gzip
  - jekyll-assets
  - jekyll-last-modified-at
